# Generated by Django 4.2.7 on 2023-11-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='boad_name',
            new_name='board_name',
        ),
    ]
