# Generated by Django 4.2.7 on 2023-11-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_boad_name_board_board_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('post_date', models.DateTimeField(verbose_name='Date posted')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
